robots:
  - name: tb1
    x_pose: 0.0
    y_pose: 0.0
    z_pose: 0.01
    yaw: 0.0
  - name: tb2
    x_pose: 3.0
    y_pose: 0.0
    z_pose: 0.01
    yaw: 3.14159
  # - name: tb2
  #   x_pose: 2.0
  #   y_pose: 1.5
  #   z_pose: 0.01
  # - name: tb3
  #   x_pose: 1.7
  #   y_pose: 0.0
  #   z_pose: 0.01
