mtsp_solver_node:
  ros__parameters:
    robot_starts: [0.0, 0.0, 10.0, 0.0, 5.0, 8.0]
    goals: [1.0, 1.0, 2.0, 3.0, 8.0, 2.0, 9.0, 5.0, 4.0, 7.0, 6.0, 6.0, 3.0, 8.0]
    population_size: 150
    generations: 300
    mutation_rate: 0.15
    seed: 42

    publish_progress: true
    generation_delay_ms: 100